name: ci

on:
  pull_request:
    branches: [main]

jobs:
  quality_check:
    name: Lint, Type Check & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' 
      - run: npm ci
      - name: Check formatting
        run: npm run format:check 
      - name: Check linting
        run: npm run lint -- --max-warnings=0
      - name: Type check
        run: npx tsc --noEmit 

      - name: Run Unit Tests
        run: npm test

  build:
    name: Build Check
    needs: quality_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Build project
        run: npm run build 
